# Generated by Django 4.2.2 on 2023-06-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('task', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
